default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: DNDTools_development
  host: localhost
  username: dndtools
  password: dndtools

test:
  <<: *default
  database: DNDTools_test
  host: localhost
  username: dndtools
  password: dndtools

production:
  <<: *default
  database: DNDTools_production
  username: DNDTools
  password: <%= ENV['DNDTOOLS_DATABASE_PASSWORD'] %>
